version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - ../static:/var/www/html/static
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email ${SSL_EMAIL:-admin@example.com} --agree-tos --no-eff-email --force-renewal -d goodmorningkr01.duckdns.org

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: web-prod
    restart: unless-stopped
    volumes:
      - ../:/app
      - ../static:/app/static
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - APP_NAME=Good Morning API
      - DEBUG=False
      - GOOGLE_APPLICATION_CREDENTIALS=/app/docker/firebase-adminsdk.json
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGINS=${CORS_ORIGINS:-https://goodmorningkr01.duckdns.org}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-goodmorningkr01.duckdns.org}
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD_SECURE:-CHANGE_THIS_PASSWORD}
      - POSTGRES_DB=mhp_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-prod
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD_SECURE:-CHANGE_THIS_PASSWORD}
      - POSTGRES_DB=mhp_db
    expose:
      - "5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-prod
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD_SECURE:-CHANGE_THIS_PASSWORD}
    volumes:
      - pgadmin_data_prod:/var/lib/pgladmin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data_prod:
  pgadmin_data_prod:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge 