version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - APP_NAME=FastAPI Firebase Auth
      - DEBUG=True
      - GOOGLE_APPLICATION_CREDENTIALS=/app/docker/firebase-adminsdk.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/docker/firebase-adminsdk.json
    command: pytest -v app/tests 